language: cpp
dist: xenial
language: cpp

git:
  depth: 1
before_install:
#g++ 8
- echo 'Installing ARM toolchain'
#- sudo apt install gcc-arm-none-eabi
- ls
- wget https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-arm-none-eabi.tar.xz
- wget https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz
- tar -Jxvf  gcc-arm-9.2-2019.12-x86_64-arm-none-eabi.tar.xz
- tar -Jxvf  gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz
- export PATH=$(pwd)/gcc-arm-9.2-2019.12-x86_64-arm-none-eabi/bin:$PATH
- export PATH=$(pwd)/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf/bin:$PATH
- echo $PATH

script:
- ./build_all.sh
- ls sd_card -l

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: Sugarbox
  skip_cleanup: true
  draft: true